import { defineType, defineField } from 'sanity';

export const article = defineType({
  name: 'article',
  title: 'Article',
  type: 'document',
  groups: [
    { name: 'content', title: 'Content', default: true },
    { name: 'meta', title: 'Meta & SEO' },
  ],
  fields: [
    defineField({
      name: 'title',
      title: 'Title',
      type: 'string',
      group: 'content',
      validation: (Rule) => Rule.required().max(100),
    }),
    defineField({
      name: 'subtitle',
      title: 'Subtitle / Deck',
      type: 'string',
      group: 'content',
      description: 'Optional subtitle that appears below the headline',
    }),
    defineField({
      name: 'slug',
      title: 'Slug',
      type: 'slug',
      group: 'content',
      options: { source: 'title', maxLength: 96 },
      validation: (Rule) => Rule.required(),
    }),
    defineField({
      name: 'author',
      title: 'Author',
      type: 'reference',
      to: [{ type: 'author' }],
      group: 'content',
      validation: (Rule) => Rule.required(),
    }),
    defineField({
      name: 'mainImage',
      title: 'Hero Image',
      type: 'image',
      group: 'content',
      options: { hotspot: true },
      fields: [
        {
          name: 'alt',
          type: 'string',
          title: 'Alt Text',
          description: 'Important for accessibility and SEO',
        },
      ],
    }),
    defineField({
      name: 'photoCredit',
      title: 'Photo Credit',
      type: 'string',
      group: 'content',
      description: 'e.g., Freelance Photographer / Impact Post',
      initialValue: 'Impact Post',
    }),
    defineField({
      name: 'mediaType',
      title: 'Media Type',
      type: 'string',
      group: 'content',
      description: 'Choose whether this article features an image or video',
      options: {
        list: [
          { title: 'Image', value: 'image' },
          { title: 'Video', value: 'video' },
        ],
        layout: 'radio',
      },
      initialValue: 'image',
    }),
    defineField({
      name: 'videoFile',
      title: 'Video File',
      type: 'file',
      group: 'content',
      options: {
        accept: 'video/*',
      },
      description: 'Upload a video file (max 12MB on free Sanity tier)',
      hidden: ({ document }) => document?.mediaType !== 'video',
    }),
    defineField({
      name: 'videoUrl',
      title: 'External Video URL',
      type: 'url',
      group: 'content',
      description: 'YouTube or Vimeo URL (use instead of file upload for large videos)',
      hidden: ({ document }) => document?.mediaType !== 'video',
    }),
    defineField({
      name: 'videoThumbnail',
      title: 'Video Thumbnail',
      type: 'image',
      group: 'content',
      options: { hotspot: true },
      description: 'Thumbnail image shown before video plays (required for videos)',
      hidden: ({ document }) => document?.mediaType !== 'video',
      fields: [
        {
          name: 'alt',
          type: 'string',
          title: 'Alt Text',
        },
      ],
    }),
    defineField({
      name: 'category',
      title: 'Content Pillar',
      type: 'reference',
      to: [{ type: 'category' }],
      group: 'content',
      validation: (Rule) => Rule.required(),
    }),
    defineField({
      name: 'tags',
      title: 'Tags',
      type: 'array',
      of: [{ type: 'string' }],
      group: 'content',
      options: { layout: 'tags' },
    }),
    defineField({
      name: 'excerpt',
      title: 'Excerpt',
      type: 'text',
      rows: 3,
      group: 'content',
      description: 'Brief summary for cards and SEO (auto-generated if empty)',
      validation: (Rule) => Rule.max(300),
    }),
    defineField({
      name: 'body',
      title: 'Content',
      type: 'blockContent',
      group: 'content',
    }),
    defineField({
      name: 'publishedAt',
      title: 'Publish Date',
      type: 'datetime',
      group: 'content',
      initialValue: () => new Date().toISOString(),
    }),
    defineField({
      name: 'isFeatured',
      title: 'Featured Article',
      type: 'boolean',
      group: 'content',
      description: 'Display as the main featured story on homepage',
      initialValue: false,
    }),
    defineField({
      name: 'placement',
      title: 'Homepage Placement',
      type: 'string',
      group: 'content',
      description: 'Where this article appears on the homepage',
      options: {
        list: [
          { title: 'Featured Hero', value: 'featured-hero' },
          { title: 'Sidebar (Community Pulse)', value: 'sidebar' },
          { title: 'Grid (Latest Stories)', value: 'grid' },
          { title: 'Featured Multimedia', value: 'featured-multimedia' },
          { title: 'Hidden', value: 'hidden' },
        ],
        layout: 'radio',
      },
      initialValue: 'grid',
    }),
    defineField({
      name: 'displayOrder',
      title: 'Display Order',
      type: 'number',
      group: 'content',
      description: 'Priority within section (1 = highest)',
      initialValue: 100,
      validation: (Rule) => Rule.min(1),
    }),
    defineField({
      name: 'pinnedUntil',
      title: 'Pinned Until',
      type: 'datetime',
      group: 'content',
      description: 'Optional: Pin article to top of section until this date',
    }),
    defineField({
      name: 'seo',
      title: 'SEO Settings',
      type: 'object',
      group: 'meta',
      options: { collapsible: true, collapsed: true },
      fields: [
        {
          name: 'metaTitle',
          type: 'string',
          title: 'Meta Title',
          description: 'Defaults to article title if empty',
        },
        {
          name: 'metaDescription',
          type: 'text',
          title: 'Meta Description',
          description: 'Defaults to excerpt if empty',
          rows: 2,
        },
        {
          name: 'socialImage',
          type: 'image',
          title: 'Social Share Image',
          description: 'Defaults to hero image if empty',
        },
      ],
    }),
    defineField({
      name: 'isSponsored',
      title: 'Sponsored Content',
      type: 'boolean',
      group: 'meta',
      description: 'Tag this article as sponsored content',
      initialValue: false,
    }),
    defineField({
      name: 'sponsor',
      title: 'Sponsor',
      type: 'reference',
      to: [{ type: 'advertisement' }],
      group: 'meta',
      description: 'Link to the advertisement campaign',
      hidden: ({ document }) => !document?.isSponsored,
    }),
  ],
  orderings: [
    {
      title: 'Publish Date, New',
      name: 'publishedAtDesc',
      by: [{ field: 'publishedAt', direction: 'desc' }],
    },
    {
      title: 'Publish Date, Old',
      name: 'publishedAtAsc',
      by: [{ field: 'publishedAt', direction: 'asc' }],
    },
  ],
  preview: {
    select: {
      title: 'title',
      author: 'author.name',
      category: 'category.title',
      media: 'mainImage',
    },
    prepare({ title, author, category, media }) {
      return {
        title,
        subtitle: `${category || 'No category'} • ${author || 'No author'}`,
        media,
      };
    },
  },
});
